# yaml-language-server: $schema=https://raw.githubusercontent.com/jesseduffield/lazygit/master/schema/config.json
git:
  overrideGpg: true
  parseEmoji: true
  diffRenderers:
    - colorArg: always
      command: delta --dark --paging=never
# Colemak
# keybinding:
#   universal:
#     prevItem-alt: "u"
#     nextItem-alt: "e"
#     prevBlock-alt: "n"
#     nextBlock-alt: "i"
#     nextMatch: "="
#     prevMatch: "-"
#     new: "k"
#     edit: "o"
#     openFile: "O"
#     scrollUpMain-alt1: "U"
#     scrollDownMain-alt1: "E"
#     scrollUpMain-alt2: "<c-u>"
#     scrollDownMain-alt2: "<c-e>"
#     undo: "l"
#     redo: "<c-r>"
#     diffingMenu: "M"
#     filteringMenu: "<c-f>"
#   files:
#     ignoreFile: "I"
#   commits:
#     moveDownCommit: "<c-e>"
#     moveUpCommit: "<c-u>"
#   branches:
#     viewGitFlowOptions: "I"
#     setUpstream: "U"
os:
  # Maybe nvim-remote:
  editPreset: "nvim"
gui:
  nerdFontsVersion: "3"
  theme:
    activeBorderColor:
      - "#75a1c7"
      - bold
    inactiveBorderColor:
      - "#404040"
    optionsTextColor:
      - "#75a1c7"
    selectedLineBgColor:
      - "#212121"
    selectedRangeBgColor:
      - "#212121"
    cherryPickedCommitBgColor:
      - "#c4a8d6"
    cherryPickedCommitFgColor:
      - "#75a1c7"
    unstagedChangesColor:
      - "#e08585"
    defaultFgColor:
      - "#e4e4e8"
    searchingActiveBorderColor:
      - "#d9a35a"
      - bold
