-- Generated by HyprMod

-- Settings
hl.config({
    general = {
        col = {
            active_border = {
                colors = {"rgba(ffb59dff)", "rgba(55200cff)"},
                angle = 90,
            },
        },
        layout = "dwindle",
    },
})

-- Monitors
hl.monitor({
    output = "DP-2",
    mode = "3840x2160@60.00Hz",
    position = "0x0",
    scale = 1,
    bitdepth = 10,
    vrr = 0,
    cm = "srgb",
    sdrbrightness = 0.5,
    sdr_min_luminance = 0.09,
    sdr_max_luminance = 308,
    min_luminance = 0.09,
    max_luminance = 308,
    max_avg_luminance = 259,
})
