-- Generated by nwg-displays on 2026-06-19 at 02:21:15. Do not edit manually.

hl.monitor({
    output = "DP-2",
    mode = "3840x2160@60.0",
    position = "0x0",
    scale = 1.0,
    bitdepth = 10
})
