# vim:fileencoding=utf-8:foldmethod=marker

# name = "luna"
# author = "wtfox"

foreground            #e4e4e8
background            #060606
cursor                #e4e4e8
cursor_text_color     #060606
selection_foreground  #e4e4e8
selection_background  #404040
tab_bar_background    #060606
active_tab_foreground #e4e4e8
active_tab_background #1c1c1c
inactive_tab_foreground #888888
inactive_tab_background #060606
bell_border_color     #e08585

color0  #000000
color1  #e08585
color2  #6fbe80
color3  #c2916a
color4  #75a1c7
color5  #c4a8d6
color6  #75a1c7
color7  #c7c7c7
color8  #888888
color9  #e08585
color10 #6fbe80
color11 #d9a35a
color12 #8c9cb8
color13 #c4a8d6
color14 #75a1c7
color15 #ffffff
